---
- name: Build artifacts
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Cargo build
    ansible.builtin.command: cargo build --release --bin murmesh-unreplicated

- name: Synchronize artifacts
  hosts: all
  gather_facts: False

  tasks:
  - name: Set work directory
    ansible.builtin.set_fact:
      work_dir: "/local/cowsay"
    when: work_dir is undefined
  - name: Synchronize
    ansible.posix.synchronize:
      src: "{{ playbook_dir }}/../../target/release/murmesh-unreplicated"
      dest: "{{ work_dir }}/"

- name: Deploy barrier service
  hosts: service
  gather_facts: False

  tasks:
  - name: Run detached
    ansible.builtin.shell:
      tmux new-session -d -s murmesh-unreplicated-service
      "{{ work_dir }}/murmesh-unreplicated
        --barrier-count {{ (groups['replica'] | length) + (groups['client'] | length) }}
        || read _"

- name: Deploy replica
  hosts: replica
  gather_facts: False

  tasks:
  - name: Run detached
    ansible.builtin.shell:
      tmux new-session -d -s murmesh-unreplicated
      "{{ work_dir }}/murmesh-unreplicated 
        --barrier-host {{ groups['service'][0] }}
        --tls
        || read _"

- name: Run clients
  hosts: client
  vars:
    some_client_count: "{{ client_count | default('1') }}"
  gather_facts: False

  tasks:
  - name: Run and collect results
    any_errors_fatal: True
    block:
    - name: Run
      ansible.builtin.shell:
        ./murmesh-unreplicated
          --barrier-host {{ groups['service'][0] }}
          --tls
          --client-index {{ (groups['client'].index(inventory_hostname) | int) * (some_client_count | int) }}
          --client-count {{ some_client_count }}
          --client-sec 10
          1> ./unreplicated-{{ inventory_hostname }}.txt
          2> ./err.log
      args:
        chdir: "{{ work_dir }}"
    - name: Synchronize
      ansible.posix.synchronize:
        mode: pull
        src: "{{ work_dir }}/unreplicated-{{ inventory_hostname }}.txt"
        dest: "{{ inventory_dir }}"
    rescue:
    - name: Report failure
      local_action:
        module: ansible.builtin.debug
        msg: "Client failed"
      run_once: True

- name: Shutdown replica
  hosts: replica
  gather_facts: False

  tasks:
  - name: Interrupt
    ansible.builtin.command: pkill -INT --full murmesh-unreplicated
    ignore_errors: True
