[package]
name = "larlis-udp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
larlis-core = { version = "0.1.0", path = "../larlis-core" }
tokio = { version = "1.27.0", features = ["net", "rt"] }
