[package]
name = "bighear_udp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bighear_core = { version = "0.1.0", path = "../bighear_core" }
tokio = { version = "1.27.0", features = ["net"] }
