[package]
name = "wm-bincode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
wm-core = { version = "0.1.0", path = "../wm-core" }
serde = "1.0.160"
