---
- name: Build artifacts
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Cargo build
    ansible.builtin.command: cargo build --release --bin larlis-unreplicated

- name: Synchronize artifacts
  hosts: all
  gather_facts: False

  tasks:
  - name: Set work directory
    ansible.builtin.set_fact:
      work_dir: "{{ override_work_dir | default('/local/cowsay') }}"
  - name: Synchronize
    ansible.posix.synchronize:
      src: "{{ playbook_dir }}/../../target/release/larlis-unreplicated"
      dest: "{{ work_dir }}/"

- name: Deploy barrier service
  hosts: service
  gather_facts: False

  tasks:
  - name: Run detached
    ansible.builtin.shell: >
      tmux new-session -d -s larlis-unreplicated-service
      "{{ work_dir }}/larlis-unreplicated --barrier-count {{ (groups['replica'] | length) + (groups['client'] | length) }} || read _"

- name: Deploy replica
  hosts: replica
  gather_facts: False

  tasks:
  - name: Run detached
    ansible.builtin.shell: >
      tmux new-session -d -s larlis-unreplicated
      "{{ work_dir }}/larlis-unreplicated --barrier-host {{ groups['service'][0] }} || read _"

- name: Run clients
  hosts: client
  vars:
    client_count: "{{ override_client_count | default('1') }}"
  gather_facts: False

  tasks:
  - name: Run and collect results
    any_errors_fatal: True
    block:
    - name: Run
      ansible.builtin.shell: >
        ./larlis-unreplicated
        --barrier-host {{ groups['service'][0] }}
        --client-index {{ (groups['client'].index(inventory_hostname) | int) * (client_count | int) }}
        --client-count {{ client_count }}
        1> ./unreplicated-{{ inventory_hostname }}.txt
        2> ./err.log
      args:
        chdir: "{{ work_dir }}"
    - name: Synchronize
      ansible.posix.synchronize:
        mode: pull
        src: "{{ work_dir }}/unreplicated-{{ inventory_hostname }}.txt"
        dest: "{{ inventory_dir }}"
    rescue:
    - name: Report failure
      local_action:
        module: ansible.builtin.debug
        msg: "Client failed"
      run_once: True

- name: Shutdown replica
  hosts: replica
  gather_facts: False

  tasks:
  - name: Interrupt
    ansible.builtin.command: pkill -INT --full larlis-unreplicated
